package com.motycka.edu.ext

fun String.normalizedFileName() = lowercase()
    .replace(" ", "-")
    .replace("/", "-")
    .replace("&", "and")
    .replace(",", "")
    .replace(":", "")
    .replace(";", "")
    .replace("(", "")
    .replace(")", "")
    .replace("[", "")
    .replace("]", "")
    .replace("{", "")
    .replace("}", "")
    .replace("'", "")
    .replace("\"", "")
    .replace("?", "")
    .replace("!", "")
    .replace("@", "at")
    .replace("#", "")
    .replace("$", "")
    .replace("%", "")
    .replace("^", "")
    .replace("*", "")
    .replace("+", "plus")
    .replace("=", "")
    .replace("|", "")
    .replace("\\", "")
    .replace("`", "")
    .replace("~", "")
    .replace("<", "")
    .replace(">", "")
